### Get all categories
GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json

### Create new category
POST http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": ""
}

### get by id
GET http://localhost:3000/api/categories/100
X-API-Key: RAHASIA
Accept: application/json

### update by id
PUT http://localhost:3000/api/categories/100
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Gadget new"
}

### get by id
DELETE http://localhost:3000/api/categories/1
X-API-Key: RAHASIA
Accept: application/json